<?php
/**
 * Created by PhpStorm.
 * User: zhipeng-finlai
 * Date: 2018/1/22
 * Time: 下午1:19
 */

namespace backend\modules\third;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'backend\modules\third\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}